name = "wordle"
description = "Wordle for the terminal"
version = "0.1.0"

authors = ["asdf"]
maintainers = ["asdf <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["wordle"]

licenses = "MIT"
tags = ["wordle", "terminal", "game"]

[[depends-on]]
aaa       = "~0.2.5"
ansiada   = "^1.0.0"
gnat      = ">=10 & <2000"  # GNAT 9 lacks some Random facilities
wordlelib = "~0.1.0-dev"
wordlist  = "~0.1.2"

[build-profiles]
'*' = "validation"

[build-switches]
'*'.Ada_Version = "GNAT_Extensions"

[[pins]]
# Local development pins
# aaa       = { path='../aaa' }
# wordlist  = { path='../wordlist_ada' }
# wordlelib = { path='../wordlelib_ada' }
